use_frameworks!
target 'RxQuickbooksService_Tests' do
    pod 'RxQuickbooksService', :path => '../'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxAlamofire'
    pod 'OAuthSwift'
    pod 'OAuthSwiftAlamofire'
    pod 'Action'
    pod 'RxCocoa'    
end

post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end